CREATE TABLE Dish
(
    Dish_Id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Name_Of_The_Dish  VARCHAR(255),
    Price_Of_The_Dish VARCHAR(255),
    CONSTRAINT pk_dish PRIMARY KEY (Dish_Id)
);

CREATE TABLE "Orders"
(
    orderId  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT,
    table_id BIGINT,
    status   VARCHAR(255),
    CONSTRAINT pk_order PRIMARY KEY (orderId)
);

CREATE TABLE OrderItem
(
    OrderItem_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Order_Id     BIGINT,
    dish_id      BIGINT,
    quantity     INTEGER                                 NOT NULL,
    CONSTRAINT pk_orderitem PRIMARY KEY (OrderItem_id)
);

CREATE TABLE "Tables"
(
    table_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_table PRIMARY KEY (table_id)
);

CREATE TABLE "Users"
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    role     VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

CREATE TABLE user_table
(
    table_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL
);

ALTER TABLE OrderItem
    ADD CONSTRAINT FK_ORDERITEM_ON_DISH FOREIGN KEY (dish_id) REFERENCES Dish (Dish_Id);

ALTER TABLE OrderItem
    ADD CONSTRAINT FK_ORDERITEM_ON_ORDER FOREIGN KEY (Order_Id) REFERENCES "Orders" (orderId);

ALTER TABLE "Orders"
    ADD CONSTRAINT FK_ORDER_ON_TABLE FOREIGN KEY (table_id) REFERENCES "Table" (table_id);

ALTER TABLE "Orders"
    ADD CONSTRAINT FK_ORDER_ON_USER FOREIGN KEY (user_id) REFERENCES "Users" (user_id);

ALTER TABLE user_table
    ADD CONSTRAINT fk_usetab_on_table_entity FOREIGN KEY (table_id) REFERENCES "Table" (table_id);

ALTER TABLE user_table
    ADD CONSTRAINT fk_usetab_on_user_entity FOREIGN KEY (user_id) REFERENCES "Users" (user_id);